/* Generated by Yosys 0.62 (git sha1 7326bb7d6641500ecb285c291a54a662cb1e76cf, clang++ 21.1.2 -fPIC -O3) */

(* cells_not_processed =  1  *)
(* src = "comparator.v:1.1-21.10" *)
module comparator_2bit_reg(clk, rst_n, a, b, less);
  (* src = "comparator.v:2.16-2.19" *)
  input clk;
  wire clk;
  (* src = "comparator.v:3.16-3.21" *)
  input rst_n;
  wire rst_n;
  (* src = "comparator.v:4.22-4.23" *)
  input [1:0] a;
  wire [1:0] a;
  (* src = "comparator.v:5.22-5.23" *)
  input [1:0] b;
  wire [1:0] b;
  (* src = "comparator.v:6.16-6.20" *)
  output less;
  wire less;
  (* src = "comparator.v:9.5-19.8" *)
  wire _0_;
  wire _1_;
  wire _2_;
  sky130_fd_sc_hd__inv_1 _3_ (
    .A(a[1]),
    .Y(_1_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_4 _4_ (
    .A(b[0]),
    .SLEEP(a[0]),
    .X(_2_)
  );
  sky130_fd_sc_hd__maj3_1 _5_ (
    .A(_1_),
    .B(b[1]),
    .C(_2_),
    .X(_0_)
  );
  (* src = "comparator.v:9.5-19.8" *)
  sky130_fd_sc_hd__dfrtp_1 _6_ (
    .CLK(clk),
    .D(_0_),
    .Q(less),
    .RESET_B(rst_n)
  );
endmodule
