/* Generated by Yosys 0.62 (git sha1 7326bb7d6641500ecb285c291a54a662cb1e76cf, clang++ 21.1.2 -fPIC -O3) */

(* cells_not_processed =  1  *)
(* src = "comparator.v:1.1-21.10" *)
module comparator_2bit_reg(clk, rst_n, a, b, less);
  (* src = "comparator.v:2.16-2.19" *)
  input clk;
  wire clk;
  (* src = "comparator.v:3.16-3.21" *)
  input rst_n;
  wire rst_n;
  (* src = "comparator.v:4.22-4.23" *)
  input [1:0] a;
  wire [1:0] a;
  (* src = "comparator.v:5.22-5.23" *)
  input [1:0] b;
  wire [1:0] b;
  (* src = "comparator.v:6.16-6.20" *)
  output less;
  wire less;
  (* src = "comparator.v:9.5-19.8" *)
  wire _0_;
  wire _1_;
  wire _2_;
  sky130_fd_sc_hd__inv_1 _3_ (
    .A(a[1]),
    .Y(_1_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_4 _4_ (
    .A(b[0]),
    .SLEEP(a[0]),
    .X(_2_)
  );
  sky130_fd_sc_hd__maj3_1 _5_ (
    .A(_1_),
    .B(b[1]),
    .C(_2_),
    .X(_0_)
  );
  (* src = "comparator.v:9.5-19.8" *)
  sky130_fd_sc_hd__dfrtp_1 _6_ (
    .CLK(clk),
    .D(_0_),
    .Q(less),
    .RESET_B(rst_n)
  );
endmodule

(* dynports =  1  *)
(* cells_not_processed =  1  *)
(* src = "pwm_generator.v:1.1-27.10" *)
module pwm_generator(clk, rst_n, duty_cycle, enable, pwm_out);
  (* src = "pwm_generator.v:4.16-4.19" *)
  input clk;
  wire clk;
  (* src = "pwm_generator.v:5.16-5.21" *)
  input rst_n;
  wire rst_n;
  (* src = "pwm_generator.v:6.28-6.38" *)
  input [7:0] duty_cycle;
  wire [7:0] duty_cycle;
  (* src = "pwm_generator.v:7.16-7.22" *)
  input enable;
  wire enable;
  (* src = "pwm_generator.v:8.16-8.23" *)
  output pwm_out;
  wire pwm_out;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  (* src = "pwm_generator.v:11.21-11.28" *)
  wire [7:0] counter;
  sky130_fd_sc_hd__xor2_1 _37_ (
    .A(counter[0]),
    .B(enable),
    .X(_00_)
  );
  sky130_fd_sc_hd__nand2_1 _38_ (
    .A(counter[0]),
    .B(enable),
    .Y(_09_)
  );
  sky130_fd_sc_hd__xnor2_1 _39_ (
    .A(counter[1]),
    .B(_09_),
    .Y(_01_)
  );
  sky130_fd_sc_hd__nand4_1 _40_ (
    .A(counter[0]),
    .B(enable),
    .C(counter[1]),
    .D(counter[2]),
    .Y(_10_)
  );
  sky130_fd_sc_hd__a31oi_1 _41_ (
    .A1(counter[0]),
    .A2(enable),
    .A3(counter[1]),
    .B1(counter[2]),
    .Y(_11_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _42_ (
    .A(_10_),
    .SLEEP(_11_),
    .X(_02_)
  );
  sky130_fd_sc_hd__xnor2_1 _43_ (
    .A(counter[3]),
    .B(_10_),
    .Y(_03_)
  );
  sky130_fd_sc_hd__inv_2 _44_ (
    .A(counter[3]),
    .Y(_12_)
  );
  sky130_fd_sc_hd__nor2_2 _45_ (
    .A(_12_),
    .B(_10_),
    .Y(_13_)
  );
  sky130_fd_sc_hd__xor2_1 _46_ (
    .A(counter[4]),
    .B(_13_),
    .X(_04_)
  );
  sky130_fd_sc_hd__nand2_1 _47_ (
    .A(counter[4]),
    .B(_13_),
    .Y(_14_)
  );
  sky130_fd_sc_hd__xnor2_1 _48_ (
    .A(counter[5]),
    .B(_14_),
    .Y(_05_)
  );
  sky130_fd_sc_hd__a31oi_1 _49_ (
    .A1(counter[4]),
    .A2(counter[5]),
    .A3(_13_),
    .B1(counter[6]),
    .Y(_15_)
  );
  sky130_fd_sc_hd__nand4_1 _50_ (
    .A(counter[4]),
    .B(counter[5]),
    .C(counter[6]),
    .D(_13_),
    .Y(_16_)
  );
  sky130_fd_sc_hd__nor2b_1 _51_ (
    .A(_15_),
    .B_N(_16_),
    .Y(_06_)
  );
  sky130_fd_sc_hd__xnor2_1 _52_ (
    .A(counter[7]),
    .B(_16_),
    .Y(_07_)
  );
  sky130_fd_sc_hd__inv_1 _53_ (
    .A(pwm_out),
    .Y(_17_)
  );
  sky130_fd_sc_hd__nand2_1 _54_ (
    .A(_12_),
    .B(duty_cycle[3]),
    .Y(_18_)
  );
  sky130_fd_sc_hd__xnor2_1 _55_ (
    .A(counter[2]),
    .B(duty_cycle[2]),
    .Y(_19_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_4 _56_ (
    .A(duty_cycle[0]),
    .SLEEP(counter[0]),
    .X(_20_)
  );
  sky130_fd_sc_hd__o21bai_2 _57_ (
    .A1(duty_cycle[1]),
    .A2(_20_),
    .B1_N(counter[1]),
    .Y(_21_)
  );
  sky130_fd_sc_hd__nand2_1 _58_ (
    .A(duty_cycle[1]),
    .B(_20_),
    .Y(_22_)
  );
  sky130_fd_sc_hd__nand4_1 _59_ (
    .A(_18_),
    .B(_19_),
    .C(_21_),
    .D(_22_),
    .Y(_23_)
  );
  sky130_fd_sc_hd__inv_1 _60_ (
    .A(duty_cycle[4]),
    .Y(_24_)
  );
  sky130_fd_sc_hd__inv_1 _61_ (
    .A(counter[2]),
    .Y(_25_)
  );
  sky130_fd_sc_hd__o22ai_1 _62_ (
    .A1(_25_),
    .A2(duty_cycle[2]),
    .B1(duty_cycle[3]),
    .B2(_12_),
    .Y(_26_)
  );
  sky130_fd_sc_hd__a22oi_2 _63_ (
    .A1(counter[4]),
    .A2(_24_),
    .B1(_18_),
    .B2(_26_),
    .Y(_27_)
  );
  sky130_fd_sc_hd__inv_1 _64_ (
    .A(duty_cycle[5]),
    .Y(_28_)
  );
  sky130_fd_sc_hd__o22ai_1 _65_ (
    .A1(counter[4]),
    .A2(_24_),
    .B1(_28_),
    .B2(counter[5]),
    .Y(_29_)
  );
  sky130_fd_sc_hd__a21oi_1 _66_ (
    .A1(_23_),
    .A2(_27_),
    .B1(_29_),
    .Y(_30_)
  );
  sky130_fd_sc_hd__inv_1 _67_ (
    .A(counter[6]),
    .Y(_31_)
  );
  sky130_fd_sc_hd__o2bb2ai_1 _68_ (
    .A1_N(counter[5]),
    .A2_N(_28_),
    .B1(duty_cycle[6]),
    .B2(_31_),
    .Y(_32_)
  );
  sky130_fd_sc_hd__inv_1 _69_ (
    .A(counter[7]),
    .Y(_33_)
  );
  sky130_fd_sc_hd__a22oi_1 _70_ (
    .A1(_31_),
    .A2(duty_cycle[6]),
    .B1(duty_cycle[7]),
    .B2(_33_),
    .Y(_34_)
  );
  sky130_fd_sc_hd__o21a_1 _71_ (
    .A1(_30_),
    .A2(_32_),
    .B1(_34_),
    .X(_35_)
  );
  sky130_fd_sc_hd__o21ai_0 _72_ (
    .A1(_33_),
    .A2(duty_cycle[7]),
    .B1(enable),
    .Y(_36_)
  );
  sky130_fd_sc_hd__o22ai_1 _73_ (
    .A1(enable),
    .A2(_17_),
    .B1(_35_),
    .B2(_36_),
    .Y(_08_)
  );
  (* src = "pwm_generator.v:13.5-25.8" *)
  sky130_fd_sc_hd__dfrtp_1 _74_ (
    .CLK(clk),
    .D(_00_),
    .Q(counter[0]),
    .RESET_B(rst_n)
  );
  (* src = "pwm_generator.v:13.5-25.8" *)
  sky130_fd_sc_hd__dfrtp_1 _75_ (
    .CLK(clk),
    .D(_01_),
    .Q(counter[1]),
    .RESET_B(rst_n)
  );
  (* src = "pwm_generator.v:13.5-25.8" *)
  sky130_fd_sc_hd__dfrtp_1 _76_ (
    .CLK(clk),
    .D(_02_),
    .Q(counter[2]),
    .RESET_B(rst_n)
  );
  (* src = "pwm_generator.v:13.5-25.8" *)
  sky130_fd_sc_hd__dfrtp_1 _77_ (
    .CLK(clk),
    .D(_03_),
    .Q(counter[3]),
    .RESET_B(rst_n)
  );
  (* src = "pwm_generator.v:13.5-25.8" *)
  sky130_fd_sc_hd__dfrtp_1 _78_ (
    .CLK(clk),
    .D(_04_),
    .Q(counter[4]),
    .RESET_B(rst_n)
  );
  (* src = "pwm_generator.v:13.5-25.8" *)
  sky130_fd_sc_hd__dfrtp_1 _79_ (
    .CLK(clk),
    .D(_05_),
    .Q(counter[5]),
    .RESET_B(rst_n)
  );
  (* src = "pwm_generator.v:13.5-25.8" *)
  sky130_fd_sc_hd__dfrtp_1 _80_ (
    .CLK(clk),
    .D(_06_),
    .Q(counter[6]),
    .RESET_B(rst_n)
  );
  (* src = "pwm_generator.v:13.5-25.8" *)
  sky130_fd_sc_hd__dfrtp_1 _81_ (
    .CLK(clk),
    .D(_07_),
    .Q(counter[7]),
    .RESET_B(rst_n)
  );
  (* src = "pwm_generator.v:13.5-25.8" *)
  sky130_fd_sc_hd__dfrtp_1 _82_ (
    .CLK(clk),
    .D(_08_),
    .Q(pwm_out),
    .RESET_B(rst_n)
  );
endmodule
